services:
    server:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/home/default/app
        ports:
            - 8000:8000
        env_file:
            - ./envfile.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./envfile.db.dev

volumes:
    postgres_data:
